# lettings/migrations/0001_initial.py

"""Initial migration for the lettings app."""

# Generated by Django 6.0.3 on 2026-03-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Database schema migration."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.PositiveIntegerField()),
                ('country_iso_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Letting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lettings.address')),
            ],
        ),
    ]
